logger:
  levels:
    ROOT: INFO
    com.pchrzasz: INFO

micronaut:
  server:
    port: ${PORT:8080}

eureka:
  client:
    registration:
      enabled: true
    defaultZone: ${EUREKA_URI:http://admin:admin@localhost:8761/eureka}
