logger:
  levels:
    ROOT: INFO
    com.pchrzasz: DEBUG

micronaut:
  server:
    port: 8080

eureka:
  client:
    registration:
      enabled: false

endpoints:
  health:
    discovery-client:
      enabled: false
