micronaut:
  application:
    name: microserviceTemplate
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
endpoints:
  all:
    path: /management
    sensitive: false
  health:
    details-visible: ANONYMOUS
    discovery-client:
      enabled: true
